# Generated by Django 4.0.5 on 2022-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=100, null=True)),
                ('probability', models.FloatField()),
                ('phisingType', models.CharField(max_length=50, null=True)),
                ('token_ko', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(null=True)),
                ('file_path', models.TextField(null=True)),
            ],
        ),
    ]
