# Generated by Django 3.2.13 on 2022-06-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugunyaneon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
                ('phisingType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='nugunyaneon',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
