# Generated by Django 4.0.5 on 2022-06-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nugunyaneon', '0002_auto_20220606_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nugunyaneon',
            new_name='FileUpload',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='phisingType',
        ),
    ]
